apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: acm-policies
spec: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-policies
  namespace: acm-policies
  annotations:
    apps.open-cluster-management.io/reconcile-rate: low

spec:
  type: GitHub
  pathname: https://github.com/apoczekalewicz/acm-policies.git
  # secretRef:
  #   name: github-credentials
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acm-policies-logs
  namespace: acm-policies
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: acm-policy
      operator: In
      values:
      - logs
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/github-path: logging/policies
  name: acm-policies-logs
  namespace: acm-policies
  labels:
    acm-policy: logs
spec:
  channel: acm-policies/acm-policies
  placement:
    local: true

